[project]
name = "mcp-crash-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "ipykernel>=6.29.5",
    "mcp>=1.12.0",
    "openai==1.75.0",
    "python-dotenv>=1.1.1",
]
